ARG DOCKER_IMAGE

FROM louisleblin/$DOCKER_IMAGE

# Additional apt-get dev packages
RUN apt-get install -y zsh curl tree vim man git

# Setting-up
RUN git clone https://github.com/louisblin/dotfiles.git ~/.dotfiles
RUN cd ~/.dotfiles && ./setup.sh -y

WORKDIR /app/w
