ARG BASE_IMAGE

FROM louisleblin/$BASE_IMAGE

# Additional apt-get dev packages
RUN apt-get install -y zsh curl tree vim man git tmux htop feh

# Setting-up a custom zsh shell + git configs
RUN git clone https://github.com/louisblin/dotfiles.git ~/.dotfiles
RUN cd ~/.dotfiles && ./setup.sh -y

# To be ran interactively
CMD ["/usr/bin/env", "zsh"]
