APP = $(notdir $(CURDIR))
SPYNNAKER_DEBUG = PRODUCTION_CODE
BUILD_DIR = build/


# Maintains the state of a Page Rank vertex
VERTEX_MODEL = $(EXTRA_SRC_DIR)/neuron/models/vertex_model_page_rank.c
VERTEX_MODEL_H = $(EXTRA_SRC_DIR)/neuron/models/vertex_model_page_rank.h


include ../Makefile.common