#!/usr/bin/env bash

# Only run on Travis for toolchain:v4.0.0
if [[ "${DOCKER_TAG_PROD}" != "v4.0.0" ]]; then
    echo "Skip testing for :${DOCKER_TAG_PROD}" && exit 0
fi


PROJECT_ROOT="`( cd \"$(dirname \"$0\")/..\" && pwd )`"
IMAGE_PROD="louisleblin/toolchain:v4.0.0"

echo "Running tests on ${IMAGE_PROD}..."

"${PROJECT_ROOT}/scripts/start_container" \
    "${IMAGE_PROD}" \
    --volume "${PROJECT_ROOT}/python:/app/w" \
    --no-pull --rm \
    --exec "python -m unittest discover -s page_rank.tests"