#!/usr/bin/env bash

set -eu

function has_image_locally {
    [[ "`docker images -q $1`" != "" ]] && return 0 || return 1
}

function push_image {
    echo "Pushing ${1} image '${2}'..."
    docker push "${2}"
}


echo -n "Push images? "

echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

IMAGE_PROD="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_PROD}"
IMAGE_DEV="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_DEV}"

has_image_locally ${IMAGE_DEV}  && push_image "dev" ${IMAGE_DEV}
has_image_locally ${IMAGE_PROD} && push_image "prod" ${IMAGE_PROD}
