#!/usr/bin/env bash

PROJECT_ROOT="`( cd \"$(dirname \"$0\")/..\" && pwd )`"

if [[ -z ${DOCKER_USERNAME} || -z ${DOCKER_IMAGE} || ${DOCKER_TAG_PROD} ]]
then
    IMAGE_PROD="louisleblin/toolchain:v4.0.0"
else
    IMAGE_PROD="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_PROD}"
fi

echo "Running tests on ${IMAGE_PROD}..."

"${PROJECT_ROOT}/scripts/start_container" \
    "${IMAGE_PROD}" \
    --volume "${PROJECT_ROOT}/python:/app/w" \
    --no-pull \
    --exec "python -m unittest discover -s page_rank.tests"