#!/usr/bin/env bash

set -eu

echo -n "Push images? "if

# If this is set
[[ ${FYP_SKIP_DOCKER_BUILD+x} ]] && echo "up to date" && exit 0
echo "needs push"

echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

IMAGE_PROD="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_PROD}"
echo "Pushing prod image '${IMAGE_PROD}'..."
docker push "${IMAGE_PROD}"

IMAGE_DEV="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_DEV}"
echo "Pushing dev image '${IMAGE_DEV}'..."
docker push "${IMAGE_DEV}"
