#!/usr/bin/env bash

echo "Setting environment for FYP..."

CURR_DIR="`( cd \"$(dirname \"$0\")\" && pwd )`"
export PATH=$PATH:"$CURR_DIR"

alias fyp-netconf="start_container -c"

#echo "Reconfiguring network settings each 1sec..."
#(while :; do sleep 1 && fyp-netconf &>/dev/null ; done) &

echo "done"
