# Use an official Python runtime as a parent image
FROM alpine:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app
ADD .spynnaker.cfg /root/.spynnaker.cfg

# Install any needed packages specified in requirements.txt
RUN apk --no-cache add python python-dev py-pip build-base libxml2-dev libxslt-dev freetype-dev libpng-dev openblas-dev dbus-x11
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Removes errors due to expected interaction
ENV DEBIAN_FRONTEND noninteractive
ENV DISPLAY :0

# Run test if not used interactively
CMD ["python", "PyNN8Examples/examples/va_benchmark.py"]
